### ISSUE TITLE
magnet links do nothing

### ISSUE THREAD

**Issue by moracabanas** [ferrolho/instant-popcorn#1]
Hi, first of all, awesome work. Im looking for a web based torrent player and found Magnet Player. The issue is I've tried some magnet links (working on webtorrent desktop app) but it doesn't work. I paste the magnet link, hit play and nothing happens. Thanks for all

**Comment by koolay** [comment]
I had the same problem for some magnet links.

**Comment by bluelephant825** [comment]
I also couldn't get a magnet link to work! I tried with 

magnet:?xt=urn:btih:9BD31756DF13CC149B62263070FB115300E1FEEC&dn=%5Bzooqle.com%5D%20Star%20Wars%20Episode%20VIII%20The%20Last%20Jedi%202017%201080p%2010bit%20BluRay%20x265%20HEVC%208CH-MRN&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.leechers-paradise.org:6969&tr=http://mgtracker.org:2710/announce&tr=http://tracker.mg64.net:6881/announce&tr=http://announce.xxx-tracker.com:2710/announce&xl=2897766236&tr=udp%3A%2F%2Feddie4.nl%3A6969&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969

**Comment by bluelephant825** [comment]
Even torrent links don't seem to work! I tried the following: https://zooqle.com/download/wq5k8.torrent

**Comment by marce1994** [comment]
Try to execute as administrator, that worked forma me.

**Comment by marce1994** [comment]
http://shareit.network of you click into download, it redirects you to instante.io with /#magnetlink AND ir seems to work :p

**Comment by marce1994** [comment]
http://shareit.network if you click into download, it redirects you to instant.io with /#magnetlink AND it seems to work :p.
You can find shareit-network repo inti my repos.

Regards! :)

**Comment by ferrolho** [comment]
![](https://i.imgur.com/23CujwO.png)

Source: https://ferrolho.github.io/magnet-player/about/

**Comment by otaviodeku-maker** [comment]
magnet:?xt=urn:btih:fe21a6a1cf0200bdb65d9fd51613516aaba787db&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.trackerfix.com%3A83%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Feddie4.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fzer0day.ch%3A1337%2Fannounce&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftorrent.gresille.org%3A80%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.btzoo.eu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.birkenwald.de%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.vraphim.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fu4.trakx.crim.ist%3A1337%2Fanunciar&tr=udp%3A%2F%2Fu6.trakx.crim.ist%3A1337%2Fannounce&tr=https%3A%2F%2Ftrackers.mlsub.net%3A443%2Fannounce&tr=udp%3A%2F%2Fp2p.publictracker.xyz%3A6969%2Fanunciar&tr=udp%3A%2F%2Fttk2.nbaonlineservice.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.fnix.net%3A6969%2Fannounce&tr=udp%3A%2F%2Fevan.im%3A6969%2Fanunciar&tr=https%3A%2F%2Ftracker.yemekyedim.com%3A443%2Fannounce&tr=udp%3A%2F%2Fmartin-gebhardt.eu%3A25%2Fanunciar&tr=udp%3A%2F%2Fr.l5.ca%3A6969%2Fanunciar
